### ISSUE TITLE
无法启用插件，因为它引起了一个致命错误（fatal error）。

### ISSUE THREAD

**Issue by windofuo** [swling/wnd-frontend#1]
当我在wordpress5.5.3中安装了这个插件，启动的时候出现以下错误：

无法启用插件，因为它引起了一个致命错误（fatal error）。

Fatal error: Uncaught Error: Class 'Wnd\Model\Wnd_Init' not found in D:\phpstudy_pro\WWW\wp-content\plugins\wnd-frontend\wnd-frontend.php:39 Stack trace: #0 D:\phpstudy_pro\WWW\wp-admin\includes\plugin.php(2255): include() #1 D:\phpstudy_pro\WWW\wp-admin\plugins.php(177): plugin_sandbox_scrape('wnd-frontend/wn...') #2 {main} thrown in D:\phpstudy_pro\WWW\wp-content\plugins\wnd-frontend\wnd-frontend.php on line 39

本地环境如下：
apache 2.4.39
mysql 5.7.26
php 7.3.4nts

**Comment by swling** [comment]
很多PHPstudy环境都出现这个问题，看上去是自动加载规则不起作用，不清楚为什么，我本地用的xampp，服务器用的lnmp环境都不存在这个问题。

**Comment by windofuo** [comment]
> 很多PHPstudy环境都出现这个问题，看上去是自动加载规则不起作用，不清楚为什么，我本地用的xampp，服务器用的lnmp环境都不存在这个问题。
我用的是phpstudy。。。怀疑是不是本地PHP环境少加载了什么组件。。。非常感谢您的回答，昨天我加你的群了，好像没通过哎。

**Comment by swling** [comment]
PHPstudy环境导致自动加载失效。
