### ISSUE TITLE
如何在支付中添加自定义字段

### ISSUE THREAD

**Issue by doocii** [swling/wnd-frontend#2]
你好，感谢开发如此强大的主题，请教如何在支付页中添加自定义字段，并在个人中心订单内显示，
<a href="https://imgtu.com/i/I9y18e"><img src="https://z3.ax1x.com/2021/11/01/I9y18e.png" alt="I9y18e.png" border="0" /></a>

**Comment by doocii** [comment]
$form->add_image_upload('header_logo', 0, 0, 'logo上传');

		$form->add_number(
			[
				'name'     => 'mobile',
				'label'    => '手机号',
				'required' => false,
			]
		);

您好，为啥，图片上传无法正常保存和返回地址？

**Comment by swling** [comment]
> ```
> 	$form->add_image_upload('header_logo', 0, 0, 'logo上传');
> 
> 	$form->add_number(
> 		[
> 			'name'     => 'mobile',
> 			'label'    => '手机号',
> 			'required' => false,
> 		]
> 	);
> ```
> 
> 您好，为啥，图片上传无法正常保存和返回地址？

你这是哪个表单类实例化的？

**Comment by swling** [comment]
> ```
> 	$form->add_image_upload('header_logo', 0, 0, 'logo上传');
> 
> 	$form->add_number(
> 		[
> 			'name'     => 'mobile',
> 			'label'    => '手机号',
> 			'required' => false,
> 		]
> 	);
> ```
> 
> 您好，为啥，图片上传无法正常保存和返回地址？

浏览器控制台返回是什么信息？
